openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ailton07/OWASP-Juice-Shop-BOLA-cases/1.0.0
  - description: SwaggerHub JuiceShop API 
    url: https://virtserver.swaggerhub.com/ailton07/JuiceShop/1.0.0
info:
  description: OWASP Juice Shop - BOLA cases
  version: "1.0.0"
  title: OWASP Juice Shop - BOLA cases
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Log-in
    description: Log-in and get User
paths:
  /rest/user/login:
    post:
      tags: ["Log-in"]
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/LoginUserResponse'
          links:
            postBasketItems:
              operationId: postBasketItems
              requestBody:
                BasketId: $response.body#/authentication.bid
            getBasketById:
              operationId: getBasketById
              parameters:
                bid: $response.body#/authentication.bid
  /rest/basket/{bid}:
    get:
      tags: ["View Basket"]
      operationId: getBasketById
      parameters:
      - name: bid
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GetBasketByIdResponse'
  /api/BasketItems:
    post:
      tags: ["Post BasketItems"]
      operationId: postBasketItems
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostBasketItemsRequest'
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/PostBasketItemsResponse'
        '400':
          description: Error resposen status code 400
        '401':
          description: Error resposen status code 401
        '500':
          description: Error resposen status code 500
components:
  schemas:
    PostBasketItemsRequest:
      type: object
      properties:
        ProductId:
          type: integer
        BasketId:
          type: string
        quantity:
          type: integer
    PostBasketItemsResponse:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            id:
              type: integer
            ProductId:
              type: integer
            BasketId:
              type: string
            quantity:
              type: integer
    LoginUserRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginUserResponse:
      type: object
      properties:
        authentication:
          type: object
          properties:
            token:
              type: string
              example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
            bid:
              type: integer
              example: 69
            umail:
              type: integer
              example: email@email.com
    GetBasketByIdResponse:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            id:
              type: integer
              example: 69
            coupon:
              type: string
              example: "Coupon"
            createdAt:
              type: string
              format: date
              example: "2021-10-25T19:15:05.901Z"
            updatedAt:
              type: string
              format: date
              example: "2021-10-25T19:15:05.901Z"
            UserId:
              type: integer
              example: 96
            Products:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Apple Juice (1000ml)"
        description:
          type: string
          example: "The all-time classic."
        price:
          type: number
          example: 1.10
        deluxePrice:
          type: number
          example: 0.99
        image:
          type: string
          example: "apple_juice.jpg"
        createdAt:
          type: string
          format: date
          example: "2021-10-25T19:38:14.178Z"
        updatedAt:
          type: string
          format: date
          example: "2021-10-25T19:38:14.178Z"
        deletedAt:
          type: string
          format: date
          example: "2021-10-25T19:38:14.178Z"